export const Users = [
  {
    id: 1,
    profilePicture: "person/nezko.jpg",
    username: "nezko",
  },
  {
    id: 2,

    profilePicture: "person/inosuke.jpg",
    username: "inosuke",
  },
  {
    id: 3,
    profilePicture: "person/kanao.jpg",
    username: "kanao",
  },
  {
    id: 4,
    profilePicture: "person/muichiro.jpg",
    username: "muichiro",
  },
  {
    id: 5,
    profilePicture: "person/muzan.jpg",
    username: "muzan",
  },
  {
    id: 6,
    profilePicture: "person/obanai.jpg",
    username: "obanai",
  },
  {
    id: 7,
    profilePicture: "person/renguko.jpg",
    username: "renguko",
  },
  {
    id: 8,
    profilePicture: "person/shinazugawa.jpg",
    username: "shinazugawa",
  },
  {
    id: 9,
    profilePicture: "person/shinobu.jpg",
    username: "shinobu",
  },
  {
    id: 10,
    profilePicture: "person/tanjiro_kamado.jpg",
    username: "tanjiro kamado",
  },
  {
    id: 11,
    profilePicture: "person/tengen.jpg",
    username: "tengen",
  },
  {
    id: 12,
    profilePicture: "person/tomiyoka.jpg",
    username: "tomiyoka",
  },
  {
    id: 13,
    profilePicture: "person/zenitsu.jpg",
    username: "zenitsu",
  },
  {
    id: 14,
    profilePicture: "person/himijima.jpg",
    username: "himijima",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/icecream.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/burger.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/cakes.png",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/chawmin.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/fried chicken.png",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/Lays.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/onigiri.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/pizza.png",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/pancakes.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/cupnoodles.jpg",
    date: "6 days ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 11,
    photo: "post/frenchfries.jpg",
    date: "1 week ago",
    userId: 11,
    like: 14,
    comment: 1,
  },
  {
    id: 12,
    desc: "Change the world by being yourself.",
    photo: "post/mix veg special.gif",
    date: "1 week ago",
    userId: 12,
    like: 101,
    comment: 22,
  },
  {
    id: 13,
    photo: "post/ramyeon.png",
    date: "2 week ago",
    userId: 13,
    like: 54,
    comment: 42,
  },
  {
    id: 14,
    desc: "Every moment is a fresh beginning.",
    photo: "post/sandwich.jpg",
    date: "2 week ago",
    userId: 14,
    like: 80,
    comment: 31,
  },
];
